import { ReduxProvider } from "./providers";
import "./globals.css";
import Footer from "./sections/Footer";

export const metadata = {
  title: "Lapify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className="flex flex-col min-h-screen">
        
        <ReduxProvider>
          <main className="flex-grow">{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
